language: go
go:
  - 1.1
  - 1.2
  - 1.3
  - 1.3.1
  - tip
before_install:
  - sudo apt-get update -qqy
  - sudo apt-get install bzr -qqy
install:
  - go get
  - go get launchpad.net/gocheck
script:
  - go test
